### ISSUE TITLE
implement repro workflow for this repo

### ISSUE THREAD

**Issue by aaronpeikert** [brandmaier/research_software_evaluation#15]

**Comment by aaronpeikert** [comment]
@brandmaier this is almost done. [You have to activate GH pages.](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch). Than you can close this issue.

**Comment by aaronpeikert** [comment]
https://github.com/brandmaier/research_software_evaluation/blob/gh-pages/manuscript.pdf

As source of GH pages you should indicate the gh-pages branch.

**Comment by brandmaier** [comment]
thanks!
