### ISSUE TITLE
First stage vs second stage algorithm

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#3]
At the moment, we don't differentiate to much between information that is collected for computing the threshold vs. for later assessment. However, many of the solutions we propose, especially evaluating whether someone adheres to best practises like unit testing, can easily be scored in the first stage and checked by students. Maybe we should discuss this.

**Comment by brandmaier** [comment]
I would rather not comment to much on the weighting yet. I feel it is too early altogether to come up with a weighting. It's more a phase of developing the indicators for now, isn't it?
