### ISSUE TITLE
ID 8: Open Source should be scored!

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#4]
If software is open source should be scored in the first phase of the algorithm, because
- OS allows parts of the software to be reused
- OS allows software to be checked for errors

Closes source software comes with many problems: Example: MPlus is often used out of conveniece, because it has a ton of features, but we have to idea how it is testes and mainted, and we don't know which bugs it hat in the past. 

One positive example is lavaan: a lot of other packages either rely directly on it, or learned from the source code! 

Whether Software is OS is therefore an aspect of rigor.

**Comment by Maximilian-Stefan-Ernst** [comment]
Also, Open Source is necessary to evaluate other aspects of rigor, like unit tests

**Comment by brandmaier** [comment]
yes!

**Comment by brandmaier** [comment]
OSI approved licenses are encouraged by penalizing closed source: https://github.com/brandmaier/research_software_evaluation/pull/14
