### ISSUE TITLE
Structure of the Paper

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#5]
I think the paper needs a general structure that is more stringend. As a starting point for discussions, I propose the following:

- initial summary of the main critique: Why no rigor for software implementations, but the same invalid metrics are used that are condemned for paper evaluation?
- discuss the problems with single metrics
  - Citations
  - GitHub Stars
  - Lines of Code
  - Date of first fully functional version
  - Open Source (is not used in phase 1)
- propose the solutions: 
  - Aspects of rigor for software -> Best practices of SE:
    - unit testing
    - CI
    - documentation
    - open source
    - bug reporting and disclosure in changelogs
    - activate maintenance
    - reproducibility
  - to measure impact, propose naming three papers that were impacted (instead of citations etc.)

**Comment by aaronpeikert** [comment]
I agree. I actually think that criticizing the indicators and coming up with the demand for and our definition of rigor for software should be our goal.

**Comment by brandmaier** [comment]
Yes. However, reproducibility is now gone as I don't see how it really fits in the software dev process here.
