### ISSUE TITLE
ID 6: Date of most recent substantive update

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#7]
In the questionnaire, the 

> Date of most recent substantive update

 is evaluated, and it explains that this 

> Indicates whether software is actively maintained. Include any release that adds substantive functionality - in semantic versioning this would be both major (X.0.0) and minor (0.X.0) releases.

However, this is an error - substantive updates do not indicate whether software is maintained. Instead, Patch releases (in semantic versioning this is 0.0.X) indicate whether software is maintained. I propose to change this, and to instead evaluate whether patch releases are done, as this is an aspect of rigor.

**Comment by brandmaier** [comment]
Yes, however, this is probably to fine-grained for the limited space we have. See my suggestion to replace the entire thing with a checkbox https://github.com/brandmaier/research_software_evaluation/pull/14
