### ISSUE TITLE
ID 7: Contributor roles and involvement

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#9]
I am not shure if we are happy with this item. Larger software project, but the same effort of the individual researcher leads to lower scores?

**Comment by brandmaier** [comment]
that's definitely a point to mention.

**Comment by brandmaier** [comment]
Mentioned now https://github.com/brandmaier/research_software_evaluation/commit/942b906f1c4cdcedef1e37d734a3e7f4f1c004ef but no solution offered.
